# Default values for casf-tomcat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#######Image Based Details
image:
  repository: sandbox-docker-inprogress.repo.lab.pl.alcatel-lucent.com/cemnovaws-lite
  tag: test
  pullPolicy: "IfNotPresent"
  replica: 2
####Service Based Details
service:
 name: cemnovaws
 type: NodePort
 nodePort: 18080
#####Resource Based Details [Calculated on Gamma Cluster]
 resources:
  requests:
    memory: 12Gi
    cpu: 500m
  limits:
    memory: 30Gi
    cpu: 6000m
###Configuration based details will be taken from configmap - cemnovaconfigmap